/*
 * 
 *  
 *  Creates an admin panel that allows the admin to edit user accounts
 */
package main;

import helpers.In;
import helpers.Out;

/**
 *
 * @author neimaykh2021
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    private In in = new In("Accounts.txt");
    private String[] input = in.readAllLines();
    private String[] account, test;
    public AdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        gotoAccountButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        dollarsTextField = new javax.swing.JTextField();
        centsTextField = new javax.swing.JTextField();
        modifyFundsButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        accountToBeModified1 = new javax.swing.JLabel();
        accountToBeModified2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Account to Modify");

        gotoAccountButton.setText("Go To Account");
        gotoAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoAccountButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Funds Available");

        dollarsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dollarsTextFieldActionPerformed(evt);
            }
        });

        centsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                centsTextFieldActionPerformed(evt);
            }
        });

        modifyFundsButton.setText("Modify Funds");
        modifyFundsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyFundsButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Current Account");

        accountToBeModified1.setText("None");

        accountToBeModified2.setText("None");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dollarsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(centsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(accountToBeModified1)
                                    .addComponent(modifyFundsButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(accountToBeModified2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(gotoAccountButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel3)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(accountToBeModified1)
                    .addComponent(accountToBeModified2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dollarsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(centsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(modifyFundsButton)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(gotoAccountButton)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void gotoAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoAccountButtonActionPerformed
            for (int i = 0; i < input.length; i++){
            account = input[i].split(" ");
            if (account[0].equals(usernameTextField.getText())){
      
                dollarsTextField.setText(account[2]);
                centsTextField.setText(account[3]);
                accountToBeModified1.setText(account[0]);
                accountToBeModified2.setText(account[1]);
                
                break;
            }
        }



        // TODO add your handling code here:
    }//GEN-LAST:event_gotoAccountButtonActionPerformed

    private void centsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_centsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_centsTextFieldActionPerformed

    private void modifyFundsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyFundsButtonActionPerformed
        // TODO add your handling code here:
        account[2] = dollarsTextField.getText();
        account[3] = centsTextField.getText();
        saveAccount();
        
        
        
    }//GEN-LAST:event_modifyFundsButtonActionPerformed

    private void dollarsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dollarsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dollarsTextFieldActionPerformed
    
    public void saveAccount(){
        Out out = new Out("Accounts.txt");
        for (int i = 0; i < input.length; i++){
            test = input[i].split(" ");
            if (test[0].equals(account[0])){
                out.println(account[0]+" "+account[1]+" "+account[2]+ " "+account[3]);
            }
            else {
                out.println(input[i]);
            }
        }
    }
    public void setAccount(String[] acc){
        account = acc;
        
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountToBeModified1;
    private javax.swing.JLabel accountToBeModified2;
    private javax.swing.JTextField centsTextField;
    private javax.swing.JTextField dollarsTextField;
    private javax.swing.JButton gotoAccountButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton modifyFundsButton;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
